version: '2'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:9.4"
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres
  web:
    build: .
    image: "docker-registry.linecorp.com/lineth/panda:vie"
    depends_on:
      - postgres
      - redis
    stdin_open: true
    labels:
      logging: 'true'
  log-router:
    privileged: true
    image: "gliderlabs/logspout"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run:/var/run:ro
      - /sys:/sys:ro
    stdin_open: true
    command:
    - syslog+tcp://10.133.70.44:12901?filter.labels=logging:true

