version: '2'
services:
  redis:
    image: "redis:alpine"
  postgres:
    image: "postgres:9.4"
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres
  web:
    build: .
    image: "docker-registry.linecorp.com/lineth/panda:vie"
    depends_on:
      - postgres
      - redis
